#cloud-config

bootcmd:
  - [ cloud-init-per, once, enable-epel,  yum-config-manager, --enable, ol7_developer_epel]

groups:
  - docker
users:
  - default
  - name: opc
    groups: docker
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL


# update package
package_update: true

# install docker, git
packages:
 - docker-engine
 - docker-compose
 - git
 - httpd
 - python36-oci-cli

runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, docker.service ]
  - [ systemctl, start, --no-block, docker.service ]
  - [ touch, /tmp/cloud-init-complete ]
  - [ systemctl, start, httpd ]
  - [ systemctl, enable, httpd.service ]
  - [ firewall-cmd, --add-service=http, --permanent ]
  - [ firewall-cmd, --zone=public, --permanent, --add-port=5000/tcp ]
  - [ firewall-cmd, --zone=public, --permanent, --add-port=80/tcp ]
  - [ firewall-cmd, --reload ]
