title: "Work VM"
description: "Provisions a development environment"
stackDescription: "Work Environment"
informationalText: "Work Environment"
schemaVersion: 1.0.1
version: "20220215"
locale: "en"

variableGroups:
- title: "Required Configuration"
  visible: true
  variables:
  - compartment_id
  - region

variables:
  compartment_id:
    type: oci:identity:compartment:id
    required: true
    visible: true
    title: "Compartment"
    description: "Compartment where your Work VM will be deployed."